// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server.proto

package proto

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	proto1 "github.com/michaelhenkel/sub/policy/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ServerRequest struct {
	// Types that are valid to be assigned to ServerResource:
	//	*ServerRequest_ResourceOne
	//	*ServerRequest_ResourceTwo
	ServerResource       isServerRequest_ServerResource `protobuf_oneof:"serverResource"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ServerRequest) Reset()         { *m = ServerRequest{} }
func (m *ServerRequest) String() string { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()    {}
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}
func (m *ServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerRequest.Unmarshal(m, b)
}
func (m *ServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerRequest.Marshal(b, m, deterministic)
}
func (m *ServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerRequest.Merge(m, src)
}
func (m *ServerRequest) XXX_Size() int {
	return xxx_messageInfo_ServerRequest.Size(m)
}
func (m *ServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerRequest proto.InternalMessageInfo

type isServerRequest_ServerResource interface {
	isServerRequest_ServerResource()
}

type ServerRequest_ResourceOne struct {
	ResourceOne *ServerResourceOne `protobuf:"bytes,1,opt,name=resourceOne,proto3,oneof" json:"resourceOne,omitempty"`
}
type ServerRequest_ResourceTwo struct {
	ResourceTwo *ServerResourceTwo `protobuf:"bytes,2,opt,name=resourceTwo,proto3,oneof" json:"resourceTwo,omitempty"`
}

func (*ServerRequest_ResourceOne) isServerRequest_ServerResource() {}
func (*ServerRequest_ResourceTwo) isServerRequest_ServerResource() {}

func (m *ServerRequest) GetServerResource() isServerRequest_ServerResource {
	if m != nil {
		return m.ServerResource
	}
	return nil
}

func (m *ServerRequest) GetResourceOne() *ServerResourceOne {
	if x, ok := m.GetServerResource().(*ServerRequest_ResourceOne); ok {
		return x.ResourceOne
	}
	return nil
}

func (m *ServerRequest) GetResourceTwo() *ServerResourceTwo {
	if x, ok := m.GetServerResource().(*ServerRequest_ResourceTwo); ok {
		return x.ResourceTwo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerRequest_ResourceOne)(nil),
		(*ServerRequest_ResourceTwo)(nil),
	}
}

type ServerResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResult) Reset()         { *m = ServerResult{} }
func (m *ServerResult) String() string { return proto.CompactTextString(m) }
func (*ServerResult) ProtoMessage()    {}
func (*ServerResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}
func (m *ServerResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResult.Unmarshal(m, b)
}
func (m *ServerResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResult.Marshal(b, m, deterministic)
}
func (m *ServerResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResult.Merge(m, src)
}
func (m *ServerResult) XXX_Size() int {
	return xxx_messageInfo_ServerResult.Size(m)
}
func (m *ServerResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResult.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResult proto.InternalMessageInfo

type ServerResourceOne struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string             `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Dtype                []string           `protobuf:"bytes,3,rep,name=dtype,proto3" json:"dgraph.type" dgraph:"ServerResourceOne"`
	SrTwo                *ServerResourceTwo `protobuf:"bytes,4,opt,name=srTwo,proto3" json:"srTwo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ServerResourceOne) Reset()         { *m = ServerResourceOne{} }
func (m *ServerResourceOne) String() string { return proto.CompactTextString(m) }
func (*ServerResourceOne) ProtoMessage()    {}
func (*ServerResourceOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}
func (m *ServerResourceOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResourceOne.Unmarshal(m, b)
}
func (m *ServerResourceOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResourceOne.Marshal(b, m, deterministic)
}
func (m *ServerResourceOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResourceOne.Merge(m, src)
}
func (m *ServerResourceOne) XXX_Size() int {
	return xxx_messageInfo_ServerResourceOne.Size(m)
}
func (m *ServerResourceOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResourceOne.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResourceOne proto.InternalMessageInfo

func (m *ServerResourceOne) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerResourceOne) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ServerResourceOne) GetDtype() []string {
	if m != nil {
		return m.Dtype
	}
	return nil
}

func (m *ServerResourceOne) GetSrTwo() *ServerResourceTwo {
	if m != nil {
		return m.SrTwo
	}
	return nil
}

type ServerResourceTwo struct {
	Name  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind  string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Dtype []string `protobuf:"bytes,3,rep,name=dtype,proto3" json:"dgraph.type" dgraph:"ServerResourceTwo"`
	//repeated string dtype = 3 [(policy.dgraph) = "ServerResourceTwo"];
	Spec                 *ResourceTwoSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServerResourceTwo) Reset()         { *m = ServerResourceTwo{} }
func (m *ServerResourceTwo) String() string { return proto.CompactTextString(m) }
func (*ServerResourceTwo) ProtoMessage()    {}
func (*ServerResourceTwo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}
func (m *ServerResourceTwo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResourceTwo.Unmarshal(m, b)
}
func (m *ServerResourceTwo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResourceTwo.Marshal(b, m, deterministic)
}
func (m *ServerResourceTwo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResourceTwo.Merge(m, src)
}
func (m *ServerResourceTwo) XXX_Size() int {
	return xxx_messageInfo_ServerResourceTwo.Size(m)
}
func (m *ServerResourceTwo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResourceTwo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResourceTwo proto.InternalMessageInfo

func (m *ServerResourceTwo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerResourceTwo) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ServerResourceTwo) GetDtype() []string {
	if m != nil {
		return m.Dtype
	}
	return nil
}

func (m *ServerResourceTwo) GetSpec() *ResourceTwoSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type ResourceTwoSpec struct {
	SpecName             string      `protobuf:"bytes,1,opt,name=specName,proto3" json:"specName,omitempty"`
	SpecValue            string      `protobuf:"bytes,2,opt,name=specValue,proto3" json:"specValue,omitempty"`
	Dtype                []string    `protobuf:"bytes,3,rep,name=dtype,proto3" json:"dgraph.type" dgraph:"ResourceTwoSpec"`
	StartRange           int32       `protobuf:"varint,4,opt,name=startRange,proto3" json:"startRange,omitempty"`
	EndRange             int32       `protobuf:"varint,5,opt,name=endRange,proto3" json:"endRange,omitempty"`
	Pol                  *proto1.Pol `protobuf:"bytes,6,opt,name=pol,proto3" json:"pol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResourceTwoSpec) Reset()         { *m = ResourceTwoSpec{} }
func (m *ResourceTwoSpec) String() string { return proto.CompactTextString(m) }
func (*ResourceTwoSpec) ProtoMessage()    {}
func (*ResourceTwoSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}
func (m *ResourceTwoSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTwoSpec.Unmarshal(m, b)
}
func (m *ResourceTwoSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTwoSpec.Marshal(b, m, deterministic)
}
func (m *ResourceTwoSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTwoSpec.Merge(m, src)
}
func (m *ResourceTwoSpec) XXX_Size() int {
	return xxx_messageInfo_ResourceTwoSpec.Size(m)
}
func (m *ResourceTwoSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTwoSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTwoSpec proto.InternalMessageInfo

func (m *ResourceTwoSpec) GetSpecName() string {
	if m != nil {
		return m.SpecName
	}
	return ""
}

func (m *ResourceTwoSpec) GetSpecValue() string {
	if m != nil {
		return m.SpecValue
	}
	return ""
}

func (m *ResourceTwoSpec) GetDtype() []string {
	if m != nil {
		return m.Dtype
	}
	return nil
}

func (m *ResourceTwoSpec) GetStartRange() int32 {
	if m != nil {
		return m.StartRange
	}
	return 0
}

func (m *ResourceTwoSpec) GetEndRange() int32 {
	if m != nil {
		return m.EndRange
	}
	return 0
}

func (m *ResourceTwoSpec) GetPol() *proto1.Pol {
	if m != nil {
		return m.Pol
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerRequest)(nil), "server.ServerRequest")
	proto.RegisterType((*ServerResult)(nil), "server.ServerResult")
	proto.RegisterType((*ServerResourceOne)(nil), "server.ServerResourceOne")
	proto.RegisterType((*ServerResourceTwo)(nil), "server.ServerResourceTwo")
	proto.RegisterType((*ResourceTwoSpec)(nil), "server.ResourceTwoSpec")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x40, 0x49, 0x93, 0x58, 0xcd, 0x24, 0x14, 0x58, 0x15, 0xb1, 0x58, 0xa0, 0x46, 0x16, 0x87,
	0xa2, 0x4a, 0xb6, 0x54, 0xc4, 0x05, 0x09, 0x90, 0xcc, 0x85, 0x13, 0xa0, 0xad, 0x85, 0x10, 0x37,
	0xc7, 0x19, 0x39, 0x51, 0x37, 0x5e, 0xb3, 0xbb, 0xc6, 0xea, 0xb5, 0xa7, 0x1e, 0xf9, 0x03, 0xbe,
	0x22, 0x3f, 0xc0, 0x81, 0xcf, 0xe8, 0x07, 0x70, 0xe4, 0x0b, 0x90, 0x77, 0x13, 0xd7, 0xb5, 0x25,
	0xe0, 0xd0, 0x93, 0x67, 0xc7, 0x6f, 0x46, 0xf3, 0x56, 0x3b, 0x30, 0x51, 0x28, 0xbf, 0xa2, 0xf4,
	0x73, 0x29, 0xb4, 0x20, 0x8e, 0x3d, 0xb9, 0x93, 0x5c, 0xf0, 0x65, 0x72, 0x66, 0xb3, 0x2e, 0xa4,
	0x22, 0x15, 0x36, 0xf6, 0xbe, 0xf7, 0xe0, 0xf6, 0x89, 0x81, 0x18, 0x7e, 0x29, 0x50, 0x69, 0xf2,
	0x12, 0xc6, 0x12, 0x95, 0x28, 0x64, 0x82, 0xef, 0x33, 0xa4, 0xbd, 0x69, 0xef, 0x70, 0x7c, 0xfc,
	0xd0, 0xdf, 0xf4, 0xdd, 0xb2, 0x35, 0xf0, 0xf6, 0x16, 0x6b, 0xf2, 0xcd, 0xf2, 0xa8, 0x14, 0x74,
	0xe7, 0x6f, 0xe5, 0x51, 0x29, 0x9a, 0xe5, 0x51, 0x29, 0xc2, 0xbb, 0xb0, 0xa7, 0xae, 0x31, 0xde,
	0x1e, 0x4c, 0xea, 0xaa, 0x82, 0x6b, 0xef, 0x67, 0x0f, 0xee, 0x75, 0xa6, 0x20, 0x04, 0x06, 0x59,
	0xbc, 0xb2, 0xe3, 0x8e, 0x98, 0x89, 0xab, 0xdc, 0xe9, 0x32, 0x9b, 0x9b, 0x19, 0x46, 0xcc, 0xc4,
	0xe4, 0x13, 0x0c, 0xe7, 0xfa, 0x2c, 0x47, 0xda, 0x9f, 0xf6, 0x0f, 0x47, 0x61, 0x78, 0xbe, 0xa6,
	0xdd, 0x6e, 0xbf, 0x2e, 0x0f, 0xc6, 0xf3, 0x54, 0xc6, 0xf9, 0xc2, 0xaf, 0xd8, 0xdf, 0x97, 0x07,
	0xae, 0x3d, 0xbe, 0xf0, 0x3a, 0xac, 0xc7, 0x6c, 0x43, 0x12, 0xc0, 0x50, 0xc9, 0x4a, 0x79, 0xf0,
	0x0f, 0x65, 0x66, 0x39, 0xef, 0x47, 0x47, 0x24, 0x2a, 0xc5, 0x0d, 0x8a, 0x44, 0xa5, 0xf8, 0x6f,
	0x91, 0x6a, 0x9e, 0xad, 0xc8, 0x11, 0x0c, 0x54, 0x8e, 0xc9, 0xc6, 0xe3, 0xc1, 0xd6, 0xa3, 0x81,
	0x9e, 0xe4, 0x98, 0x30, 0x03, 0x79, 0x17, 0x3b, 0x70, 0xa7, 0xf5, 0x87, 0xb8, 0xb0, 0x5b, 0xfd,
	0x7b, 0x77, 0xa5, 0x51, 0x9f, 0xc9, 0x23, 0x18, 0x55, 0xf1, 0xc7, 0x98, 0x17, 0xb8, 0xf1, 0xb9,
	0x4a, 0x90, 0xe8, 0xba, 0xd4, 0xab, 0xf3, 0x35, 0x6d, 0x77, 0xef, 0x2a, 0xd1, 0xad, 0x52, 0x8b,
	0xac, 0x85, 0x9e, 0x00, 0x28, 0x1d, 0x4b, 0xcd, 0xe2, 0x2c, 0x45, 0xa3, 0x35, 0x0c, 0x07, 0x17,
	0x6b, 0x0a, 0xac, 0x91, 0x27, 0x53, 0xd8, 0xc5, 0x6c, 0x6e, 0x99, 0xa1, 0x65, 0xbe, 0xad, 0xe9,
	0x3e, 0xab, 0xb3, 0xe4, 0x31, 0xf4, 0x73, 0xc1, 0xa9, 0x63, 0xee, 0x65, 0xec, 0x6f, 0x76, 0xea,
	0x83, 0xe0, 0xac, 0xca, 0x1f, 0xbf, 0x06, 0xc7, 0x5e, 0x2a, 0x79, 0x0e, 0xce, 0x1b, 0x89, 0xb1,
	0x46, 0x72, 0xbf, 0xfd, 0x0a, 0xcc, 0x8e, 0xb9, 0xfb, 0x9d, 0xc7, 0x51, 0x70, 0x1d, 0x1e, 0x7d,
	0x7e, 0x9a, 0x2e, 0xf5, 0xa2, 0x98, 0xf9, 0x89, 0x58, 0x05, 0xab, 0x65, 0xb2, 0x88, 0x91, 0x2f,
	0x30, 0x3b, 0x45, 0x1e, 0xa8, 0x62, 0x16, 0xd8, 0x9a, 0xc0, 0x2c, 0xee, 0xcc, 0x31, 0x9f, 0x67,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x65, 0x59, 0x0a, 0xf1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	Create(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*ServerResult, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Create(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*ServerResult, error) {
	out := new(ServerResult)
	err := c.cc.Invoke(ctx, "/server.Server/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	Create(context.Context, *ServerRequest) (*ServerResult, error)
}

// UnimplementedServerServer can be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (*UnimplementedServerServer) Create(ctx context.Context, req *ServerRequest) (*ServerResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Server/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Create(ctx, req.(*ServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Server_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
